#!/bin/bash
# Usage-metrics extension — enables OpenClaw's built-in diagnostics
# Prometheus exporter and hands the running gateway's own auth token to
# Prometheus for scraping. Runs at container start, every start (matches
# the other extensions' idempotent pattern).
set -euo pipefail

# The diagnostics-prometheus plugin is an official ClawHub package, not
# bundled with OpenClaw core (unlike the stock diagnostics-otel exporter) —
# install it if it isn't already present.
if ! node openclaw.mjs plugins list 2>/dev/null | grep -qi diagnostics-prometheus; then
    node openclaw.mjs plugins install clawhub:@openclaw/diagnostics-prometheus >/dev/null 2>&1 \
      && echo "Installed diagnostics-prometheus plugin." \
      || echo "Warning: failed to install diagnostics-prometheus plugin"
fi

node openclaw.mjs plugins enable diagnostics-prometheus >/dev/null 2>&1 \
  && echo "Enabled diagnostics-prometheus plugin." \
  || echo "Warning: failed to enable diagnostics-prometheus plugin"

node openclaw.mjs config patch --stdin << 'JSONEOF' >/dev/null 2>&1 \
  && echo "Configured diagnostics.enabled." \
  || echo "Warning: failed to configure diagnostics.enabled"
{ diagnostics: { enabled: true } }
JSONEOF

# Hand Prometheus the gateway's own operator token so it can authenticate
# to /api/diagnostics/prometheus (same token used for `openclaw health
# --token`, already generated by entrypoint.sh into .openclaw/data/.env —
# see docker-compose.metrics.yml's prometheus service, which mounts the
# file this writes).
#
# NOTE: on a genuinely first-ever container start, this runs BEFORE
# entrypoint.sh generates OPENCLAW_GATEWAY_TOKEN (extension install scripts
# run before that step), so .env won't have it yet on that one run. One
# more `docker compose restart` after the token exists is enough to pick
# it up — see .openclaw/README.md's "Usage metrics" section.
OPENCLAW_ENV="/home/node/.openclaw/.env"
TOKEN_FILE="/home/node/.openclaw/prometheus-scrape-token"
if [ -f "$OPENCLAW_ENV" ] && grep -q "^OPENCLAW_GATEWAY_TOKEN=" "$OPENCLAW_ENV"; then
    grep "^OPENCLAW_GATEWAY_TOKEN=" "$OPENCLAW_ENV" | cut -d= -f2- > "$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
    echo "Wrote Prometheus scrape token."
else
    echo "Warning: OPENCLAW_GATEWAY_TOKEN not yet generated — Prometheus scrape token not written this run. Restart once more after it exists."
fi
